### ISSUE TITLE
[FEATURE] <description>Adding preloader to child therapy page

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#556]
### Description

I would like to add to  preloader child therapy page

**Comment by AdityaPrasad275** [comment]
Hello there! I followed a quick yt tutorial for this and have the following changes for this ->

childTherapy.html - 
```diff
<body>
+ <div class="preloader">
+   </div>

<!-- Navbar Section -->
    <nav>
```
```diff
  </footer>
  <script src="childTherapy.js"></script>

+ <script>
+    var loader = document.querySelector(".preloader");

+   window.addEventListener("load", function(){
+     loader.style.display = "none";
+    });
+ </script>

  </body>
```

childTherapy.css (all additions)
```css
.preloader {
  height: 100vh;
  width: 100%; 
  background: #1C1B1B url(../images/comp_4.gif) no-repeat center center; 
  position: fixed; 
  z-index: 100;
  background-size: 25%;
}
```

Used a simple pre loader gif and tailored the background with respect to the gif.

Does this meet the specifications / demands for the feature? Should i open a PR with these changes
